In [2]:
import pandas as pd
import numpy as np

In [24]:
cols = ['education', 'age', 'capital-gain', 'race', 'capital-loss', 'hours-per-week', 'sex', 'classification']
cns = pd.read_csv('Datasets/census.data', names=cols)

In [25]:
cns.head()

education  age capital-gain   race  capital-loss  hours-per-week     sex  \
0  Bachelors   39         2174  White             0              40    Male   
1  Bachelors   50            ?  White             0              13    Male   
2    HS-grad   38            ?  White             0              40    Male   
3       11th   53            ?  Black             0              40    Male   
4  Bachelors   28            0  Black             0              40  Female   

  classification  
0          <=50K  
1          <=50K  
2          <=50K  
3          <=50K  
4          <=50K

In [26]:
cns.dtypes

education         object
age                int64
capital-gain      object
race              object
capital-loss       int64
hours-per-week     int64
sex               object
classification    object
dtype: object

In [27]:
cns['capital-gain'].unique()

array(['2174', '?', '0', '14084', '5178', '5013', '2407', '14344', '15024',
       '7688', '34095', '4064', '4386', '7298', '1409', '3674', '1055',
       '3464', '2050', '2176', '594', '6849', '4101', '1111', '3411',
       '2597', '25236', '4650', '9386', '2463', '3103', '10605', '2964',
       '3325', '2580', '3471', '4865', '6514', '1471', '2329', '99999',
       '20051', '2105', '2885', '25124', '10520', '2202', '2961', '27828',
       '6767', '8614', '2228', '1506', '13550', '2635', '5556', '4787',
       '3781', '3137', '3818', '3942', '914', '401', '2829', '2977',
       '4934', '2062', '15020', '1424', '3273', '22040', '4416', '10566',
       '991', '4931', '1086', '7430', '6497', '114', '7896', '2346',
       '3432', '2907', '1151', '2414', '2290', '3418', '15831', '41310',
       '4508', '5455', '2538', '3456', '3908', '1848', '3887', '5721',
       '9562', '6418', '1455', '2036', '1831', '11678', '2936', '2993',
       '7443', '6360', '2354', '1797', '1173', '4687', '2009',

In [28]:
# need to convert value "?" to NaN. 
# there are at least two ways to do that: 
# 1. add na_values = ['?'] when load DataFrame.
# 2. df['column_name'] = pd.to_numeric(df['column_name]', errors='coerce')
# (The errors='coerce' parameter instructs Pandas to enter a NaN at any field 
# where the conversion fails.)
cns = pd.read_csv('Datasets/census.data', names=cols, na_values=['?'])

In [29]:
cns.head()

education  age  capital-gain   race  capital-loss  hours-per-week     sex  \
0  Bachelors   39        2174.0  White             0              40    Male   
1  Bachelors   50           NaN  White             0              13    Male   
2    HS-grad   38           NaN  White             0              40    Male   
3       11th   53           NaN  Black             0              40    Male   
4  Bachelors   28           0.0  Black             0              40  Female   

  classification  
0          <=50K  
1          <=50K  
2          <=50K  
3          <=50K  
4          <=50K

In [32]:
cns.dtypes

education          object
age                 int64
capital-gain      float64
race               object
capital-loss        int64
hours-per-week      int64
sex                object
classification     object
dtype: object

In [33]:
cns['sex'].unique()

array(['Male', 'Female'], dtype=object)

In [34]:
cns['classification'].unique()

array(['<=50K', '>50K'], dtype=object)

In [35]:
cns['race'].unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo',
       'Other'], dtype=object)

In [38]:
cns['hours-per-week'].unique()

array([40, 13, 16, 45, 50, 80, 30, 35, 60, 20, 44, 15, 25, 38, 43, 55, 48,
       58, 32, 70,  2, 22, 56, 41, 28, 24, 46, 12, 65, 42,  1, 36, 10, 34,
       75, 98, 54,  8,  6, 19, 18, 72,  5,  9, 47, 37, 21, 64, 26, 14,  4,
       59, 33,  7, 52, 99, 53, 39, 62, 57, 78, 90, 66, 11, 49, 84, 17, 68,
       27,  3, 85, 31, 51, 77, 63, 23, 87, 88, 73, 89, 97, 94, 29, 96, 67,
       82, 86, 91, 81, 76, 92, 61, 74, 95])

In [39]:
cns['capital-loss'].unique()

array([   0, 2042, 1408, 1573, 1902, 1887, 1719, 1762, 2179, 1816, 1980,
       1977, 1876, 1340, 2206, 1741, 1485, 1564, 2339, 2415, 1721, 1380,
       2051, 2352, 1672,  653, 2392, 1504, 2001, 1590, 1651, 1628, 1848,
       1740, 2002, 1579, 2258, 1669, 1602,  419, 2547, 2174, 2205, 1138,
       2238,  625, 2377,  213, 1539,  880, 1092, 1594, 3004, 2231, 1844,
        810, 2559, 2057, 1974,  974, 1825, 1735, 1258, 2129, 2603, 2282,
        323, 4356, 2444, 2246, 2149, 1617, 1648, 2824, 2489, 3770, 1755,
       3683, 1668, 1726, 2267, 2457,  155, 3900, 2201, 1944, 2467, 2163,
       2754, 2472, 1411])

In [43]:
cns['education'].unique().sort()

None


In [42]:
cns['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       '7th-8th', 'Doctorate', '5th-6th', '10th', '1st-4th', 'Preschool',
       '12th'], dtype=object)

In [44]:
ordered_ed = ['1st-4th','5th-6th','7th-8th','9th','10th','11th','12th',
              'HS-grad','Preschool','Some-college','Bachelors','Masters',
              'Doctorate']

In [50]:
cns['encoded_education'] = cns['education'].astype('category', ordered=True,
                                           categories=ordered_ed).cat.codes

In [52]:
cns.head()

education  age  capital-gain   race  capital-loss  hours-per-week     sex  \
0  Bachelors   39        2174.0  White             0              40    Male   
1  Bachelors   50           NaN  White             0              13    Male   
2    HS-grad   38           NaN  White             0              40    Male   
3       11th   53           NaN  Black             0              40    Male   
4  Bachelors   28           0.0  Black             0              40  Female   

  classification  encoded_ed  encoded_education  
0          <=50K          10                 10  
1          <=50K          10                 10  
2          <=50K           7                  7  
3          <=50K           5                  5  
4          <=50K          10                 10

In [54]:
cns = cns.drop('encoded_ed',axis=1)

In [55]:
cns['encoded_education'].unique()

array([10,  7,  5, 11,  3,  9,  2, 12,  1,  4,  0,  8,  6])

In [49]:
ordered_classif = ['<=50K','>50K']

In [56]:
cns['encoded_classification'] = cns['classification'].astype('category',
                        ordered=True, categories=ordered_classif).cat.codes

In [57]:
cns.head()

education  age  capital-gain   race  capital-loss  hours-per-week     sex  \
0  Bachelors   39        2174.0  White             0              40    Male   
1  Bachelors   50           NaN  White             0              13    Male   
2    HS-grad   38           NaN  White             0              40    Male   
3       11th   53           NaN  Black             0              40    Male   
4  Bachelors   28           0.0  Black             0              40  Female   

  classification  encoded_education  encoded_classification  
0          <=50K                 10                       0  
1          <=50K                 10                       0  
2          <=50K                  7                       0  
3          <=50K                  5                       0  
4          <=50K                 10                       0

In [58]:
cns.encoded_classification.unique()

array([0, 1])

In [60]:
cns = pd.get_dummies(cns,columns=['race','sex'])

In [61]:
cns.head()

education  age  capital-gain  capital-loss  hours-per-week classification  \
0  Bachelors   39        2174.0             0              40          <=50K   
1  Bachelors   50           NaN             0              13          <=50K   
2    HS-grad   38           NaN             0              40          <=50K   
3       11th   53           NaN             0              40          <=50K   
4  Bachelors   28           0.0             0              40          <=50K   

   encoded_education  encoded_classification  race_Amer-Indian-Eskimo  \
0                 10                       0                      0.0   
1                 10                       0                      0.0   
2                  7                       0                      0.0   
3                  5                       0                      0.0   
4                 10                       0                      0.0   

   race_Asian-Pac-Islander  race_Black  race_Other  race_White  sex_Female  \
0                      0.0         0.0         0.0         1.0         0.0   
1                      0.0         0.0         0.0         1.0         0.0   
2                      0.0         0.0         0.0         1.0         0.0   
3                      0.0         1.0         0.0         0.0         0.0   
4                      0.0         1.0         0.0         0.0         1.0   

   sex_Male  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0

In [62]:
cns.drop(['education', 'classification'],axis=1)

age  capital-gain  capital-loss  hours-per-week  encoded_education  \
0       39        2174.0             0              40                 10   
1       50           NaN             0              13                 10   
2       38           NaN             0              40                  7   
3       53           NaN             0              40                  5   
4       28           0.0             0              40                 10   
5       37           0.0             0              40                 11   
6       49           0.0             0              16                  3   
7       52           0.0             0              45                  7   
8       31       14084.0             0              50                 11   
9       42        5178.0             0              40                 10   
10      37           0.0             0              80                  9   
11      30           0.0             0              40                 10   
12      23           0.0             0              30                 10   
13      34           0.0             0              45                  2   
14      25           0.0             0              35                  7   
15      32           0.0             0              40                  7   
16      38           0.0             0              50                  5   
17      43           0.0             0              45                 11   
18      40           0.0             0              60                 12   
19      54           0.0             0              20                  7   
20      35           0.0             0              40                  3   
21      43           0.0          2042              40                  5   
22      59           0.0             0              40                  7   
23      56           0.0             0              40                 10   
24      19           0.0             0              40                  7   
25      54           0.0             0              60                  9   
26      39           0.0             0              80                  7   
27      49           0.0             0              40                  7   
28      20           0.0             0              44                  9   
29      45           0.0          1408              40                 10   
...    ...           ...           ...             ...                ...   
29506   30           0.0             0              55                  7   
29507   32           0.0             0              40                  4   
29508   22           0.0             0              40                  9   
29509   31           0.0             0              40                  7   
29510   29           0.0             0              35                  7   
29511   35           0.0             0              55                 10   
29512   30           0.0             0              99                 10   
29513   34           0.0             0              60                 12   
29514   54           0.0             0              50                 10   
29515   37           0.0             0              39                  9   
29516   22           0.0             0              35                  6   
29517   34           0.0             0              55                 10   
29518   30           0.0             0              46                  7   
29519   38       15020.0             0              45                 10   
29520   71           0.0             0              10                 12   
29521   45           0.0             0              40                  7   
29522   41           0.0             0              32                  7   
29523   72           0.0             0              25                  7   
29524   31           0.0             0              30                 11   
29525   43           0.0             0              40                  7   
295